### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by petertriho** [petertriho/nix-config#3]
## TODO:
- [x] support barebone machines (pc, laptops)
- [ ] gh action to update `lazy-lock.json` 
- [ ] gh action to update `flake.lock` -> builds packages, pushes this to cache
- [x] bootstrap should add --accept-flake-config
- [x] bootstrap should install git (not available on nixos)

**Comment by petertriho** [comment]
## basic t480 config 
[configuration.nix.txt](https://github.com/user-attachments/files/16302320/configuration.nix.txt)
[hardware-configuration.nix.txt](https://github.com/user-attachments/files/16302321/hardware-configuration.nix.txt)
[t480.nix.txt](https://github.com/user-attachments/files/16302323/t480.nix.txt)
https://wiki.nixos.org/wiki/Fwupd
secure boot? https://github.com/nix-community/lanzaboote
manage partitions https://github.com/nix-community/disko

**Comment by petertriho** [comment]
# nix-darwin
- [ ] homebrew env variables
- [ ] keymaps
- [ ] set `defaults` https://macos-defaults.com/
- [ ] fix `vim` config
